### PR TITLE
Update Readme and related documentation

### PR DESCRIPTION
**Pull request by johnnonweiler**
This makes no significant changes to contents, but rewords a lot of the English language, moves some bits around (including moving the installation guide into a separate file), and tidies up some of the formatting.

Checklist
- [x] Source is rebased on latest `upstream main` so is mergeable automatically or easily merged even with confliction.
- [x] Title of this PR is meaningful: e.g. "fix issue #8 geomPipeline.py -o does not work", not "fix geomPipeline.py"
- [x] Commit message is meaningful:  `git push origin +your_branch` to squash some tiny fixes for CI failures
- [x] Give the maintainer the legal rights to change the open source license in the future (see wiki/Contribution.md) for details

### CODE REVIEW

**Comment by johnnonweiler** [comment]
I think it is a bit tricky to see the changes from looking at the diffs.  I suggest looking at the new versions here: https://github.com/johnnonweiler/parallel-preprocessor/blob/update-readme/Readme.md and https://github.com/johnnonweiler/parallel-preprocessor/blob/update-readme/wiki/Installation.md .

**Comment by qingfengxia** [comment]
CI is working on your fork and on PR,  some of them is cancelled, no sure why. 

I see you have split out installation.md, to make readme me clean. thank you

**Comment by johnnonweiler** [comment]
@qingfengxia - I have rebased and fixed the conflicts.

**Review by qingfengxia — COMMENTED** [review]
Installation.md has been split out ,  thank you

**Pull request merged**
